#!/bin/bash
# Cleanup script to remove output CSV files
# These can be regenerated anytime by running the semantic matching system

echo "Cleaning up output CSV files..."
echo "These files are generated outputs and can be regenerated."
echo ""

# Count files before
count=$(ls -1 best_models_*.csv 2>/dev/null | wc -l | tr -d ' ')

if [ "$count" -eq 0 ]; then
    echo "No best_models_*.csv files found to clean up."
    exit 0
fi

echo "Found $count output CSV file(s):"
ls -1 best_models_*.csv

echo ""
read -p "Delete these files? (y/n): " confirm

if [ "$confirm" = "y" ] || [ "$confirm" = "Y" ]; then
    rm -f best_models_*.csv
    echo "✓ Deleted $count file(s)"
    echo ""
    echo "Note: These files can be regenerated by running:"
    echo "  python3 get_best_models_semantic.py --config configs/usecase_config.json"
else
    echo "Cancelled. No files deleted."
fi

